"""add readers

Revision ID: 562ef4ec2979
Revises: 4767f89e9cec
Create Date: 2022-04-28 00:41:56.115233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562ef4ec2979'
down_revision = '4767f89e9cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readers_id'), 'readers', ['id'], unique=False)
    op.add_column('books', sa.Column('reader_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_books_reader_id'), 'books', ['reader_id'], unique=False)
    op.create_foreign_key(None, 'books', 'readers', ['reader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_reader_id'), table_name='books')
    op.drop_column('books', 'reader_id')
    op.drop_index(op.f('ix_readers_id'), table_name='readers')
    op.drop_table('readers')
    # ### end Alembic commands ###
